import { LanguageOption } from "../types";

/**
 * ANGEL CENTRALIZED LANGUAGE REGISTRY
 * Single source of truth for all language capabilities across text, speech synthesis, 
 * live transcription, and conversational reasoning.
 */

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  {
    code: "auto",
    name: "Auto Detection",
    nativeName: "Automatic",
    flag: "🌐",
    region: "Dynamic Multilingual",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Hey. I'm Angel. What's up?",
  },
  {
    code: "en-US",
    name: "English (US)",
    nativeName: "English",
    flag: "🇺🇸",
    region: "United States",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Hey. I'm Angel. What's up?",
  },
  {
    code: "en-GB",
    name: "English (UK)",
    nativeName: "English (UK)",
    flag: "🇬🇧",
    region: "United Kingdom",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Hello. I'm Angel. How are things?",
  },
  {
    code: "en-NG",
    name: "English (Nigeria)",
    nativeName: "Nigerian English",
    flag: "🇳🇬",
    region: "West Africa",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Hey. Angel here. How far now?",
  },
  {
    code: "es-ES",
    name: "Spanish",
    nativeName: "Español",
    flag: "🇪🇸",
    region: "Spain / Latin America",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Hola, soy Angel. ¿Qué tal?",
  },
  {
    code: "fr-FR",
    name: "French",
    nativeName: "Français",
    flag: "🇫🇷",
    region: "France / Francophonie",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Salut, je suis Angel. Comment ça va ?",
  },
  {
    code: "de-DE",
    name: "German",
    nativeName: "Deutsch",
    flag: "🇩🇪",
    region: "Germany / Austria / Switzerland",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Hallo, ich bin Angel. Was hast du vor?",
  },
  {
    code: "ja-JP",
    name: "Japanese",
    nativeName: "日本語",
    flag: "🇯🇵",
    region: "Japan",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "こんにちは、エンジェルです。どうしたの？",
  },
  {
    code: "ko-KR",
    name: "Korean",
    nativeName: "한국어",
    flag: "🇰🇷",
    region: "South Korea",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "안녕, 엔젤이야. 무슨 일 있어?",
  },
  {
    code: "pt-BR",
    name: "Portuguese (Brazil)",
    nativeName: "Português do Brasil",
    flag: "🇧🇷",
    region: "Brazil",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Oi, sou a Angel. Tudo bem?",
  },
  {
    code: "it-IT",
    name: "Italian",
    nativeName: "Italiano",
    flag: "🇮🇹",
    region: "Italy",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Ciao, sono Angel. Come stai?",
  },
  {
    code: "zh-CN",
    name: "Chinese (Mandarin)",
    nativeName: "中文 (普通话)",
    flag: "🇨🇳",
    region: "China / Singapore",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "嗨，我是 Angel。最近怎么样？",
  },
  {
    code: "zh-HK",
    name: "Chinese (Cantonese)",
    nativeName: "粵語 (廣東話)",
    flag: "🇭🇰",
    region: "Hong Kong / Guangdong",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "哈囉，我係 Angel。近排點呀？",
  },
  {
    code: "ar-SA",
    name: "Arabic",
    nativeName: "العربية",
    flag: "🇸🇦",
    region: "Middle East & North Africa",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "مرحباً، أنا آنجل. كيف حالك؟",
  },
  {
    code: "hi-IN",
    name: "Hindi",
    nativeName: "हिन्दी",
    flag: "🇮🇳",
    region: "India",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "नमस्ते, मैं एंजेल हूँ। सब कैसा चल रहा है?",
  },
  {
    code: "yo-NG",
    name: "Yoruba",
    nativeName: "Èdè Yorùbá",
    flag: "🇳🇬",
    region: "Nigeria / West Africa",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Báwo, èmi ni Angel. Ṣé àlàáfíà ni?",
  },
  {
    code: "ig-NG",
    name: "Igbo",
    nativeName: "Ásụ̀sụ́ Ìgbò",
    flag: "🇳🇬",
    region: "Nigeria / West Africa",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Kèdú, abụ m Angel. Kèdú kwanụ?",
  },
  {
    code: "ha-NG",
    name: "Hausa",
    nativeName: "Harshen Hausa",
    flag: "🇳🇬",
    region: "West & Central Africa",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Sannu, ni ce Angel. Yaya kake?",
  },
  {
    code: "sw-KE",
    name: "Swahili",
    nativeName: "Kiswahili",
    flag: "🇰🇪",
    region: "East Africa",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Habari, mimi ni Angel. Mambo vipi?",
  },
  {
    code: "nl-NL",
    name: "Dutch",
    nativeName: "Nederlands",
    flag: "🇳🇱",
    region: "Netherlands / Belgium",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Hoi, ik ben Angel. Hoe gaat het?",
  },
  {
    code: "pl-PL",
    name: "Polish",
    nativeName: "Polski",
    flag: "🇵🇱",
    region: "Poland",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Cześć, tu Angel. Co tam słychać?",
  },
  {
    code: "tr-TR",
    name: "Turkish",
    nativeName: "Türkçe",
    flag: "🇹🇷",
    region: "Turkey",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Selam, ben Angel. Nasıl gidiyor?",
  },
  {
    code: "ru-RU",
    name: "Russian",
    nativeName: "Русский",
    flag: "🇷🇺",
    region: "Eastern Europe & Central Asia",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Привет, я Энджел. Как дела?",
  },
  {
    code: "sv-SE",
    name: "Swedish",
    nativeName: "Svenska",
    flag: "🇸🇪",
    region: "Sweden",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Hej, jag är Angel. Läget?",
  },
  {
    code: "vi-VN",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
    flag: "🇻🇳",
    region: "Vietnam",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Chào bạn, mình là Angel. Dạo này thế nào?",
  },
  {
    code: "id-ID",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    flag: "🇮🇩",
    region: "Indonesia",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Hai, aku Angel. Apa kabar?",
  },
  {
    code: "th-TH",
    name: "Thai",
    nativeName: "ไทย",
    flag: "🇹🇭",
    region: "Thailand",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "สวัสดีค่ะ ฉันคือ Angel เป็นยังไงบ้างคะ?",
  },
  {
    code: "el-GR",
    name: "Greek",
    nativeName: "Ελληνικά",
    flag: "🇬🇷",
    region: "Greece",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "Γεια σου, είμαι η Angel. Τι νέα;",
  },
  {
    code: "he-IL",
    name: "Hebrew",
    nativeName: "עברית",
    flag: "🇮🇱",
    region: "Israel",
    hasText: true,
    hasSpeech: true,
    hasTranscription: true,
    samplePhrase: "היי, אני אנג'ל. מה העניינים?",
  },
];

export function getLanguageByCode(code?: string): LanguageOption {
  if (!code) return SUPPORTED_LANGUAGES[0];
  const normalized = code.toLowerCase().trim();
  const found = SUPPORTED_LANGUAGES.find(
    (l) =>
      l.code.toLowerCase() === normalized ||
      l.code.toLowerCase().startsWith(normalized.slice(0, 2))
  );
  return found || SUPPORTED_LANGUAGES[0];
}

export function searchLanguages(query: string): LanguageOption[] {
  const q = query.toLowerCase().trim();
  if (!q) return SUPPORTED_LANGUAGES;
  return SUPPORTED_LANGUAGES.filter(
    (lang) =>
      lang.name.toLowerCase().includes(q) ||
      lang.nativeName.toLowerCase().includes(q) ||
      lang.code.toLowerCase().includes(q) ||
      (lang.region && lang.region.toLowerCase().includes(q))
  );
}
